const height = document.querySelector('#height')
const weight = document.querySelector('#weight')
const goals = document.querySelector('#goals')
const result_Btn = document.querySelector('#result')
console.log(height, weight, goals, result_Btn)